name: Slither Smart Contract Audit

on:
  push:
    branches:
      - master
jobs:
  audit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '2.7.18'
    - name: Install Slither
      run: pip install slither-analyzer
    - name: Run Slither
      run: slither .
