name: Slither Smart Contract Audit

on:
  push:
    branches:
      - master
jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Slither
      run: |
          python -m venv /tmp/pip-audit-env
          source /tmp/pip-audit-env/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
    - name: Run pip-audit
      uses: trailofbits/gh-action-pip-audit@v0.0.4
      with:
          virtual-environment: /tmp/pip-audit-env
