name: Slither Smart Contract Audit

on:
  push:
    branches:
      - master
jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Truffle
      run: npm install -g truffle
    - name: Install Slither
      run: pip install slither-analyzer
    - name: Compile Contracts
      run: npx truffle compile --all
    - name: Run Slither
      run: slither --json report.json .
    - name: Upload Slither report
      uses: actions/upload-artifact@v2
      with:
        name: Slither report
        path: report.json
